export default {
	DISTRICT_LIST_REQUEST: 'DISTRICT_LIST_REQUEST',
	DISTRICT_LIST_SUCCESS: 'DISTRICT_LIST_SUCCESS',
	DISTRICT_LIST_ERROR: 'DISTRICT_LIST_ERROR',
	SELECTED_DISTRICT_ITEM: 'SELECTED_DISTRICT_ITEM'
}