export default {
    PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
    VERIFY_USER_SUCCEEDED: 'VERIFY_USER_SUCCEEDED',
    VERIFY_USER_FAILED: 'VERIFY_USER_FAILED',
    CHANGE_PASSWORD_SUCCEEDED: 'CHANGE_PASSWORD_SUCCEEDED',
    CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED'
}