export default {
    USER_SEARCH_REQUEST: 'USER_SEARCH_REQUEST',
    VOTER_SEARCH_SUCCESS: 'VOTER_SEARCH_SUCCESS',
    CAPTAIN_SEARCH_SUCCESS: 'CAPTAIN_SEARCH_SUCCESS',
    VOTER_SEARCH_ERROR: 'VOTER_SEARCH_ERROR',
    CAPTAIN_SEARCH_ERROR: 'CAPTAIN_SEARCH_ERROR'
};