const VoterContants = {
	VOTER_LIST_REQUEST: 'VOTER_LIST_REQUEST',
	VOTER_LIST_SUCCESS: 'VOTER_LIST_SUCCESS',
	VOTER_LIST_ERROR: 'VOTER_LIST_ERROR',
	VOTER_UPDATE_SUCCESS: 'VOTER_UPDATE_SUCCESS',
	VOTER_UPDATE_ERROR: 'VOTER_UPDATE_ERROR',
	VOTER_ADD_SUCCESS: 'VOTER_ADD_SUCCESS',
	VOTER_ADD_ERROR: 'VOTER_ADD_ERROR',
	VOTER_DELETE_SUCCESS: 'VOTER_DELETE_SUCCESS',
	VOTER_DELETE_ERROR: 'VOTER_DELETE_ERROR'
};

export default VoterContants