export default {
    register: '/register',
    profile: '/profile',
    makelist: '/make_list',
    pageDown: '/page_down',
    noTaskErr: '/no_task_error',
    invites: '/invites',
    tasksList: '/task_list',
    voterList: '/voter_list',
    community: '/community',
    captainsDashboard: '/home',
    adminDashboard: '/home_admin',
    messageList: '/message_list',
    login: '/',
    voterDetail: '/voter_detail',
    matchList: '/match_list',
    voterSuccess: '/voter_success',
    voterNotFoundError: '/voter_not_found',
    welcome: '/welcome',
    forum: '/forum',
    reports: '/reports',
    addVoterTask: '/task/add_voters',
    literatureTextTask: '/task/literature_text',
    literatureVideoTask: '/task/literature_video',
    recruitingCaptainTask: '/task/recruiting_captains',
    registerVoterTask: '/task/register_voters',
    updateProfileTask: '/task/update_profile',
    preferenceTask: '/task/preference',
    mailRegistrationTask: '/task/mail_registration',
    reminderVoteTask: '/task/reminder_vote',
    regularVoteTask: '/task/regular_vote',

    voterFilter: '/voter_filter',
    captainFilter: '/captain_filter',
    verifyCaptain: '/changePassword/verify',
    changePassword: '/changePassword/change',
    forgotPassword: '/changePassword/request',

    loglist: '/transaction_logs/list',
    logdetail: '/transaction_logs/detail',

    whyBetheWave: '/why_BetheWave',
    howContribute: '/contribute',
    termsOfUse: '/terms_of_use',
    privacyPolicy: '/privacy_policy',
    faq: '/faq',
    resourceCenter: '/resource_center',

    unsubscribe: '/unsubscribe/:email'
}
