export default {
    register: '/captainProfile/Register',
    makelist: '/captainProfile/MakeList',
    pageDown: '/errorPages/Page_50_X',
    invites: '/invites/SendInvite',
    tasksList: '/tasksList',
    voterList: '/voterList',
    community: '/community',
    captainsDashboard: '/captainsDashboard',
    adminDashboard: '/adminDashboard',
    messageList: '/messageList',
    login: '/',
    voterDetail: '/voterDetail',
    matchList: '/matchList',
    voterSuccess: '/voterSuccess',
    voterNotRegisteredError: '/voterNotRegisteredError',
    voterNotFoundError: '/voterNotFoundError',
    forum: '/forum',
    reports: '/reports',
    addVoterTask: '/task/addVoters',
    literatureTextTask: '/task/literatureText',
    literatureVideoTask: '/task/literatureVideo',
    recruitingCaptainTask: '/task/recruitingCaptains',
    registerVoterTask: '/task/registerVoters',
    updateProfileTask: '/task/updateProfile',
    preferenceTask: '/task/preferenceTask',
    mailRegistrationTask: '/task/mailRegistrationTask',
    reminderVoteTask: '/task/reminderVoteTask',
    regularVoteTask: '/task/regularVoteTask',

    voterFilter: '/voterFilter',
    captainFilter: '/captainFilter',
    verifyCaptain: '/changePassword/verify',
    changePassword: '/changePassword/change',
    forgotPassword: '/changePassword/request',

    loglist: '/transactionLogs/list',
    logdetail: '/transactionLogs/detail',

    whyBetheWave: '/whyBetheWave',
    howContribute: '/howYouCanContribute',
    termsOfUse: '/termsOfUse',
    privacyPolicy: '/privacyPolicy',
    faq: '/faq',

    unsubscribe: '/unsubscribe/:email'
}
