export default {
    signUp: '/signup',
    profile: '/settings/profile',
    pageDown: '/page_down',
    tasksList: '/task_list',
    voterList: '/voter_list',
    addVoter: '/add_voter',
    captainsDashboard: '/home',
    leaderboard: '/leaderboard',
    adminDashboard: '/home_admin',
    helpCenter: '/help_center',
    signIn: '/',
    voterDetail: '/voter_detail',
    matchList: '/match_list',
    welcome: '/welcome',
    selectDistrict: '/select_district',
    socialConnect: '/social_connect',
    selectVoters: '/select_voters',
    voterFilter: '/voter_filter',
    captainFilter: '/captain_filter',
    changePassword: '/change_password/change/:token',
    forgotPassword: '/change_password/request',
    verifyEmail: '/verify_email',
    connectGoogle: '/connectGoogle',
    connectTwitter: '/connectTwitter',
    sendToGoogle: '/sendToGoogle',
    sendToTwitter: '/sendToTwitter',

    // static
    termsAndConditions: '/terms_conditions'
}
